language: rust

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc

rust:
  - stable
  - beta
  - nightly

env:
  global:
    - CARGO_ARGS=""

matrix:
  include:
    - rust: nightly
      env: CARGO_ARGS="--features clippy"
  allow_failures:
    - env: CARGO_ARGS="--features clippy"

before_script: (cargo install rustfmt || true)

script:
  - export PATH="${PATH}:${HOME}/.cargo/bin"
  - export RUST_BACKTRACE=1
  - scripts/run_tests.sh
  - cargo bench

after_success:
  - scripts/build_kcov.sh
  - scripts/send_kcov.sh
  - bash <(curl -s https://codecov.io/bash)
